### ISSUE TITLE
Tracking issue: partial SGR code support

### ISSUE THREAD

**Issue by bugadani** [bugadani/embedded-text#52]
- [ ] 0 Reset
 - [ ] 4 Underline
 - [ ] 9 Crossed out 
 - [ ] 24 Underline off
 - [ ] 29 Not crossed out
 - [ ] 39 Default foreground color
 - [ ] 49 Default background color
